security:
  oauth2:
    client:
      clientId: @googleClientID@
      clientSecret: @googleClientSecret@
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientAuthenticationScheme: form
      scope: https://www.googleapis.com/auth/drive
    resource:
      userInfoUri: https://www.googleapis.com/drive/v3/about?fields=user

logging:
  level:
    org.springframework.security: DEBUG

spring:
  profiles:
    active: linux
  datasource:
    url: jdbc:h2:file:~/db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
  jpa.hibernate.ddl-auto: update

cloudfuse:
  fuse:
    defaults:
      automount: false
      googledrive:
        localFolder: /tmp/mnt
        remoteFolder: cloudfuse